###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-15 22:37:38
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-11-08 19:32:03
###############################################################

invokables :
	Text : Element/Form/Element/TextFormElement
	Textarea : Element/Form/Element/TextareaFormElement
	Button : Element/Form/Element/ButtonFormElement
	Select : Element/Form/Element/SelectFormElement